# Generated by Django 4.2.3 on 2023-08-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
